### ISSUE TITLE
Support CLI interface

### ISSUE THREAD

**Issue by alonbhaim** [mockoon/cli#1]
Is there way to run mockoon without UI ? I want to use mockoon on UNIX-like operating systems without GUI.

**Comment by 255kb** [comment]
Dear people interested in the CLI. You will be happy (we hope 🤞) to learn that we just published a beta version of it. 🥳https://www.npmjs.com/package/@mockoon/cli
It's quite clean and stable, but still, it's a beta version, and we will need your feedback to improve it. 😃 
After several months of work, we will need to give some love to the main application, but we will closely follow the evolution of this tool. 

We will announce its availability next week. Until then, do not hesitate to tinker with it and tell us [what you think](https://github.com/mockoon/cli/discussions).

Thanks for your patience. 🚀
