### ISSUE TITLE
Cannot start Mockoon CLI when installed locally instead of globally 

### ISSUE THREAD

**Issue by fgrmt** [mockoon/cli#13]
**Describe the bug**
Mockoon CLI cannot start when installed locally instead of globally.

**To Reproduce**
* **Step 1:** install mockoon CLI **locally**
``` shell
npm install @mockoon/cli --save-dev
```

* **Step 2:** start mockoon using npx
``` shell
npx mockoon start --data servers.json --name myMockServer
```

* **Step 3:** get an error
```
 ›   Error: Cannot start myMockServer due to errors (see errors in /Users/[redacted]/.mockoon-cli/logs/myMockServer-error.log)
```
Related error log:

``` js
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module '/usr/local/lib/node_modules/@mockoon/cli/node_modules/pm2/lib/ProcessContainerFork.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Expected behavior**
Mockoon should be able to run as a local package.

Local install of Mockoon CLI would allow great use cases such as:
* deploying it and using it on CI/CD PaaS solutions or hosting platforms where NPM global installation is prohibited
* using it as a dev dependency integrated with other tools (e2e testing, etc.)

**Mockoon version:**
 @mockoon/cli/0.1.0-beta.2 darwin-x64 node-v15.4.0

**OS / OS version:**
Mac OS 11.1 Big Sur

**Comment by 255kb** [comment]
@fgrmt we tested on various environments including MacOS Big Sur with the same Node version and weren't able to reproduce. 
Could you check if you may have a conflict with some globally installed packages like PM2? Also did you install Mockoon globally before? It looks like your global NPM cache may be "corrupted" somehow.

**Comment by fgrmt** [comment]
Mockoon was indeed installed globally before.

So I tried to figure out what was happening with my NPM cache.

**Running `npm cache verify` followed by a reboot somehow fixed this issue.**

@255kb Thanks a lot for your help and for all the good work on Mockoon and Mockoon CLI which are easily two of best tools I discovered in 2020! 👏

**Comment by 255kb** [comment]
We are glad you solved your problem!
Thank you for the kind words 😊
