### ISSUE TITLE
Server from cli should be able to start from openAPI file

### ISSUE THREAD

**Issue by kecsolecso** [mockoon/cli#16]
Currently, only a mockoon export file is supported.
Whoever wants to work with cli they have no use of UI.
It is cumbersome to start the GUI to import an openAPI file just to export it then

**Comment by 255kb** [comment]
This is true that OpenAPI could be supported by the CLI out of the box. 
Could I kindly ask you to edit your issue and follow the [feature template](https://github.com/mockoon/cli/issues/new?assignees=&labels=&template=Feature_request.md)? Thank you.

**Comment by mauriceackel** [comment]
I opened a feature request according to the template for this as I think this would be a nice feature 🚀. So maybe we can close this one here 🎉

**Comment by 255kb** [comment]
Thank you @mauriceackel will close this one then :)
