### ISSUE TITLE
Base 64 encoding in templates not working

### ISSUE THREAD

**Issue by michaelbuchar** [mockoon/cli#17]
**Describe the bug**
When using the mocking-cli tool as opposed to the Mockoon application, my response to one of the POST requests is: Error while serving the content: btoa is not defined. I am using the base64 encoding in my mock API tool. In the Mockoon application everything works as intended.

**To Reproduce**
Steps to reproduce the behavior.
"source": "mockoon:1.11.0",
    "data": [
        {
            "type": "environment",
            "item": {
                "uuid": "",
                "lastMigration": 13,
                "name": "Demo API",
                "endpointPrefix": "",
                "latency": 0,
                "port": 3000,
                "routes": [
                    {
                        "uuid": "",
                        "documentation": "Generate Artifactory body (JSON) with templating",
                        "method": "post",
                        "endpoint": "artifactory/api/security/token",
                        "responses": [
                            {
                                "uuid": "",
                                "body": "{\n \"access_token\": \"{{# base64}}\"iat\":{{ now 't' }},\"jti\":\"{{ faker 'random.uuid' }}\"}{{/ base64}}",
                                "latency": 0,
                                "statusCode": 200,
                                "label": "",
                                "headers": [
                                    {
                                        "key": "",
                                        "value": ""
                                    }
                                ],
                                "filePath": "",
                                "sendFileAsBody": false,
                                "rules": [],
                                "rulesOperator": "OR",
                                "disableTemplating": false
                            },
                            {
                                "uuid": "",
                                "body": "{}",
                                "latency": 0,
                                "statusCode": 404,
                                "label": "",
                                "headers": [
                                    {
                                        "key": "",
                                        "value": ""
                                    }
                                ],
                                "filePath": "",
                                "sendFileAsBody": false,
                                "rules": [],
                                "rulesOperator": "OR",
                                "disableTemplating": false
                            }
                        ],
                        "enabled": true,
                        "randomResponse": false
                    },

**Expected behavior**
It is expected to pass the correct access token back from the POST API call yet it creates a 200 Status (OK) response but the Body states: _Error while serving the content: btoa is not defined_

**Mockoon version:**
1.11.0

**OS / OS version:**
Mac OS - Version 10.15.7

**Comment by 255kb** [comment]
Thanks for noticing @michaelbuchar we are indeed using a method not supported on Node.js 🤦 
This will be fixed for next update (end of Feb-early March)

**Comment by michaelbuchar** [comment]
Thanks a lot!
