### ISSUE TITLE
feat: OpenApi description as input file

### ISSUE THREAD

**Issue by mauriceackel** [mockoon/cli#18]
This is a follow-up to #16 using the feature template.

**Is your feature request related to a problem? Please describe.**
When you are using the cli, you need to reference a file that was exported by the Mockoon GUI. If one only has an OpenAPI description file he/she would need to use the UI first to convert this file to a Mockoon environment.

**Describe the solution you'd like**
Users should be able to also use OpenApi spec files as input and the cli should automatically covert them and start a mock server.
Perhaps, an optional cli parameter should be added to the respective commands (i.e. `start` or `dockerize`) that signals the type of the input file (the default should be the Mockoon environment format).
If a OpenApi file is used as input, the cli should first attempt to convert the file to an environment and then start the environment.

**Describe alternatives you've considered**
An alternative would be to adda command to the cli that can convert from OpenApi to Mockoon environment, this would make the input to the `start` command to always be a Mockoon environment (like it is now). However, the user experience would suffer, as there need to be two command executed. Furthermore, there could be issues if the file is not on a local machine but on a server and loaded via an URL.

**Additional context**
To achieve this functionality, code from the Mockoon GUI can very likely be reused. The relevant code is probably in this file: https://github.com/mockoon/mockoon/blob/adf52c5f9b9bd71330e9b59d424cb92130bdd2e7/src/app/services/openapi-converter.service.ts . The core conversion functionality could be added to the `commons` repository, ming it available to both the GUI and the CLI.

**Comment by 255kb** [comment]
@mauriceackel I think we could have the two features. What I imagined was a behind the scene conversion when detecting an OpenAPI spec file. 
But a command could also be useful. 
I will work on this soon :)

**Comment by mauriceackel** [comment]
🎉

**Comment by 255kb** [comment]
> 🎉

Sorry for the wait 😅
