### ISSUE TITLE
-bash: mockoon-cli: command not found

### ISSUE THREAD

**Issue by insub** [mockoon/cli#20]
npm install successful but mockoon-cli: command not found

**OS / OS version:**
Mac OS 10.15.7

**Node version:**
v12.20.0

**Mockoon Cli version:**
+ @mockoon/cli@0.1.0-beta.6

**Comment by 255kb** [comment]
Which command did you run? `npm i -g @mockoon/cli` or `npm i @mockoon/cli`? With the latter the package is installed locally and you will need to run it with `npx mockoon-cli`.

**Comment by insub** [comment]
I run `npm i -g @mockoon/cli` , I suspect it is a problem with my local npm environment, let me confirm it first

**Comment by 255kb** [comment]
You may want to try to uninstall/reinstall the package, and even clean NPM's cache. 
We didn't have any report of a failing command, so hopefully it's your setup and it's easy to solve 😃
