### ISSUE TITLE
run multiple environments at the same time

### ISSUE THREAD

**Issue by Eitol** [mockoon/cli#24]
When I try to run the cli with using a file that has multiple environments, I must make a call for each one, when I really want to be able to run all of them

By adding an "all" flag to the "start" command, you could make it easier to run all environments at the same time.
example: 

mockoon-cli start --data ~/export-data.json --all

I can contribute with this feature :)

**Comment by 255kb** [comment]
@Eitol thanks for opening this issue. 
You can go for it if you want. Please do not forget to add tests for this new flag, and keep the implementation simple. I am thinking of looping through all environments and trying to run them, outputting all success or error messages (if something went wrong like unavailable port, name already taken).

**Comment by Eitol** [comment]
Hello, I have already made the change. In macOS Big Sur the integration tests do not work well (those of the master branch without any modification). Tonight I'm going to keep working to get the fault

**Comment by 255kb** [comment]
Be sure to update to the `main` branch (yes, it has been renamed) and to clean your node_modules and run npm install again. A lot of things changed with the tests setup in the past months and it should definitely work on MacOS. If it's still not working, do not hesitate to push and open a PR. The CI runs for all commit on a PR, so you can just wait a bit for the tests to run.
