### ISSUE TITLE
Integration tests do not work in macOS Big Sur

### ISSUE THREAD

**Issue by Eitol** [mockoon/cli#25]
Integration tests fail when run on macOS Big Sur, making development difficult.

Trying to access the debugger, it can be seen that the text of the context.message variable is the following:
"Cannot start mockoon-mock2 due to errors (see errors in /Users/USER/.mockoon-cli/logs/mockoon-mock2-error.log)"

![image](https://user-images.githubusercontent.com/1043061/116482013-50202280-a852-11eb-93c7-ce4177af1e6f.png)

But if we go to the log file we find that if it contains the text:

![image](https://user-images.githubusercontent.com/1043061/116482475-37643c80-a853-11eb-900b-5a84303e367c.png)

**Mockoon CLI version:**
0.1.0-beta.10

**OS / OS version:**
macOS Big Sur (Intel)

Notes: I will try to fix the problem

**Comment by 255kb** [comment]
From what I see the tests are working well, but port 3000 is already in use. The tests are automatically stopping all running processes before starting, however, if you have another app running on port 3000 it won't work.
