### ISSUE TITLE
docker cli reload data from URL without restart

### ISSUE THREAD

**Issue by seevik2580** [mockoon/cli#27]
Hello, i was curious if there is a way to achieve this...
i have data on http://example.blablabla/file.json
running docker container with `docker run -d -p 3000:3000 mockoon/cli:latest -d http://example.blablabla/file.json -i 0 -p 3000`
and after i change some data inside http://example.blablabla/file.json that new data isnt loaded inside docker container until i restart my container.. is there a way to make it automatically without container restart? thanks alot

**Comment by seevik2580** [comment]
solved it with gitlab CI/CD and kubernetes

**Comment by 255kb** [comment]
I am glad you figured it out. As you saw the CLI is not monitoring data files for changes. You have to either restart the CLI or the Docker container.
