### ISSUE TITLE
Request history/logging

### ISSUE THREAD

**Issue by StummeJ** [mockoon/cli#34]
**Is your feature request related to a problem? Please describe.**
Yes - using the mockoon app you can see the history of requests, in the CLI you cannot.  Also while using the docker image there is no feedback if a request is not fulfilled

**Describe the solution you'd like**
Have a web interface that shows the requests that were made to the mocked endpoints

**Describe alternatives you've considered**
A console log that shows the responses

**Additional context**
https://mockoon.com/docs/latest/requests-logging/

**Comment by 255kb** [comment]
After discussing with multiple users I think we are heading toward more info in the log files. A web interface would be a lot of work, and is not a priority right now. 
Concerning Docker, I think it would be covered by #33.
