### ISSUE TITLE
add field Endpointprefix in cli list 

### ISSUE THREAD

**Issue by saravanan30erd** [mockoon/cli#45]
Hi Team,

Usually the `moockon-cli list` provides the below output,

```
Name         Id      Status       Cpu        Memory       Hostname       Port   
mockoon-test1  1    online     0.3       45.7 MB      0.0.0.0       3000
```

As we know that every mock service runs on its own port. so If we want to manage all mock services in single domain using path based routing, we need some sort of load balancer or reverse proxy in front of all these mock services.

https://mock.example.com/api/test1 (Reverse proxy) ----> http://localhost:3000/api/test1

It is very difficult when we have 100s of mock services running, each and every time we need to make changes in load balancer configuration whenever we add new mock services or changes in mock services. To automate this process, two fields are majorly required such as `Port` and `endpointPrefix`. `Port` is already provided in `cli list` command so If we make `endpointPrefix` available in `list` command then it will be very useful for load balancer configuration automation process.

Example, [ReadyAPI cli](https://support.smartbear.com/virtserver/docs/user-tasks/cli.html) provides this functionality in `list` so I created easily the [clustering model](https://github.com/saravanan30erd/traefik-readyapi-virtserver).

Expected output:
```
Name                  Id   Status    Cpu    Memory    Hostname       Port     endpointPrefix
mockoon-test1   1    online    0.3       45.7 MB      0.0.0.0          3000    /api/test1
```

**Comment by saravanan30erd** [comment]
Hi @255kb , Could you please check this issue & its PR and provide your feedback?

**Comment by 255kb** [comment]
https://github.com/mockoon/cli/releases/tag/v1.2.1 😊
