### ISSUE TITLE
Include body and headers of requests on the logs

### ISSUE THREAD

**Issue by jbaris** [mockoon/cli#56]
**Is your feature request related to a problem? Please describe.**
I need to see the body of incoming POST request on logs. By running: 
```
docker run -d --mount type=bind,source=/home/username/your-data-file.json,target=/data,readonly -p 3000:3000 mockoon/cli:latest -d data -i 0 -p 3000
```
I see the logs like:
```
mockoon_1  | {"level":"info","message":"POST / | 200","timestamp":"2022-01-19T17:35:32.614Z"}
mockoon_1  | {"level":"info","message":"POST /users | 200","timestamp":"2022-01-19T17:35:48.956Z"}
```
It will be useful to see the body and headers of the request.

**Describe the solution you'd like**
Allow to specify by a parameter to increase the logs details of incoming http requests.

**Comment by 255kb** [comment]
This is now possible with the `--log-transaction` flag. You will get the same information you see in the desktop app. 
Be careful, logs will be quite big with this option.

**Comment by jbaris** [comment]
@255kb thank you for the answer and doc!
